// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: AGR1_ControlCenter

#ifndef _AGR1_CONTROLCENTER_UI_H
#define _AGR1_CONTROLCENTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * SCAN_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
