// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: AGR1_ControlCenter

#include "ui.h"

// COMPONENT DeviceListItem

lv_obj_t * ui_DeviceListItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_DeviceListItem;
    cui_DeviceListItem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_DeviceListItem);
    lv_obj_set_width(cui_DeviceListItem, 326);
    lv_obj_set_height(cui_DeviceListItem, 50);
    lv_obj_set_x(cui_DeviceListItem, -423);
    lv_obj_set_y(cui_DeviceListItem, 161);
    lv_obj_set_align(cui_DeviceListItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_DeviceListItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_DeviceListItem, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_DeviceListItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_DeviceListItem, lv_color_hex(0x910202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_DeviceListItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_DeviceListItemTitle;
    cui_DeviceListItemTitle = lv_label_create(cui_DeviceListItem);
    lv_obj_set_width(cui_DeviceListItemTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_DeviceListItemTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_DeviceListItemTitle, LV_ALIGN_CENTER);
    lv_label_set_text(cui_DeviceListItemTitle, "DeviceListItemTitle");

    lv_obj_t * cui_DeviceListItemButton;
    cui_DeviceListItemButton = lv_button_create(cui_DeviceListItem);
    lv_obj_set_width(cui_DeviceListItemButton, 100);
    lv_obj_set_height(cui_DeviceListItemButton, 32);
    lv_obj_set_align(cui_DeviceListItemButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_DeviceListItemButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_DeviceListItemButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_DeviceListItemButtonLabel;
    cui_DeviceListItemButtonLabel = lv_label_create(cui_DeviceListItemButton);
    lv_obj_set_width(cui_DeviceListItemButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_DeviceListItemButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_DeviceListItemButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_DeviceListItemButtonLabel, "text");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DEVICELISTITEM_NUM);
    children[UI_COMP_DEVICELISTITEM_DEVICELISTITEM] = cui_DeviceListItem;
    children[UI_COMP_DEVICELISTITEM_DEVICELISTITEMTITLE] = cui_DeviceListItemTitle;
    children[UI_COMP_DEVICELISTITEM_DEVICELISTITEMBUTTON] = cui_DeviceListItemButton;
    children[UI_COMP_DEVICELISTITEM_DEVICELISTITEMBUTTON_DEVICELISTITEMBUTTONLABEL] = cui_DeviceListItemButtonLabel;
    lv_obj_add_event_cb(cui_DeviceListItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_DeviceListItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_DeviceListItem_create_hook(cui_DeviceListItem);
    return cui_DeviceListItem;
}

