// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: AGR1_ControlCenter

#ifndef _UI_COMP_DEVICELISTITEM_H
#define _UI_COMP_DEVICELISTITEM_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT DeviceListItem
#define UI_COMP_DEVICELISTITEM_DEVICELISTITEM 0
#define UI_COMP_DEVICELISTITEM_DEVICELISTITEMTITLE 1
#define UI_COMP_DEVICELISTITEM_DEVICELISTITEMBUTTON 2
#define UI_COMP_DEVICELISTITEM_DEVICELISTITEMBUTTON_DEVICELISTITEMBUTTONLABEL 3
#define _UI_COMP_DEVICELISTITEM_NUM 4
lv_obj_t * ui_DeviceListItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
