// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: AGR1_ControlCenter

#include "ui.h"

lv_obj_t * uic_WeatherTab;
lv_obj_t * ui_Screen;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_WeatherTab;
lv_obj_t * ui_DeviceListItem;
lv_obj_t * ui_BluetoothTab;
lv_obj_t * ui_ContainerBLEDeviceList;
lv_obj_t * ui_Label2;
lv_obj_t * ui_buttonScanBLE;
lv_obj_t * ui_Label3;
lv_obj_t * ui_DeviceInfoTab;
lv_obj_t * ui_WiFiTab;

// event funtions

// build funtions

void ui_Screen_screen_init(void)
{
    ui_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_TabView1 = lv_tabview_create(ui_Screen);
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_x(ui_TabView1, 1);
    lv_obj_set_y(ui_TabView1, 0);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherTab = lv_tabview_add_tab(ui_TabView1, "Weather");
    lv_obj_set_flex_flow(ui_WeatherTab, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WeatherTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_grad_color(ui_WeatherTab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceListItem = ui_DeviceListItem_create(ui_WeatherTab);
    lv_obj_set_width(ui_DeviceListItem, 326);
    lv_obj_set_height(ui_DeviceListItem, 36);
    lv_obj_set_x(ui_DeviceListItem, -373);
    lv_obj_set_y(ui_DeviceListItem, -54);

    ui_BluetoothTab = lv_tabview_add_tab(ui_TabView1, "BLE Devices");
    lv_obj_set_flex_flow(ui_BluetoothTab, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BluetoothTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_ContainerBLEDeviceList = lv_obj_create(ui_BluetoothTab);
    lv_obj_remove_style_all(ui_ContainerBLEDeviceList);
    lv_obj_set_width(ui_ContainerBLEDeviceList, 400);
    lv_obj_set_height(ui_ContainerBLEDeviceList, 350);
    lv_obj_set_x(ui_ContainerBLEDeviceList, -88);
    lv_obj_set_y(ui_ContainerBLEDeviceList, 10);
    lv_obj_set_align(ui_ContainerBLEDeviceList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerBLEDeviceList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerBLEDeviceList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ContainerBLEDeviceList, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ContainerBLEDeviceList);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Found BLE Devices:");

    ui_buttonScanBLE = lv_button_create(ui_BluetoothTab);
    lv_obj_set_width(ui_buttonScanBLE, 100);
    lv_obj_set_height(ui_buttonScanBLE, 50);
    lv_obj_set_align(ui_buttonScanBLE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonScanBLE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonScanBLE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_buttonScanBLE);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Scan");

    ui_DeviceInfoTab = lv_tabview_add_tab(ui_TabView1, "Device Info");
    lv_obj_set_flex_flow(ui_DeviceInfoTab, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DeviceInfoTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_WiFiTab = lv_tabview_add_tab(ui_TabView1, "WiFi Devices");

    uic_WeatherTab = ui_WeatherTab;

}

void ui_Screen_screen_destroy(void)
{
    if(ui_Screen) lv_obj_del(ui_Screen);

    // NULL screen variables
    ui_Screen = NULL;
    ui_TabView1 = NULL;
    uic_WeatherTab = NULL;
    ui_WeatherTab = NULL;
    ui_DeviceListItem = NULL;
    ui_BluetoothTab = NULL;
    ui_ContainerBLEDeviceList = NULL;
    ui_Label2 = NULL;
    ui_buttonScanBLE = NULL;
    ui_Label3 = NULL;
    ui_DeviceInfoTab = NULL;
    ui_WiFiTab = NULL;

}
