// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: AGR1_ControlCenter

#ifndef UI_SCREEN_H
#define UI_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen
extern void ui_Screen_screen_init(void);
extern void ui_Screen_screen_destroy(void);
extern lv_obj_t * ui_Screen;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_WeatherTab;
extern lv_obj_t * ui_DeviceListItem;
extern lv_obj_t * ui_BluetoothTab;
extern lv_obj_t * ui_ContainerBLEDeviceList;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_buttonScanBLE;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_DeviceInfoTab;
extern lv_obj_t * ui_WiFiTab;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WeatherTab;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

